# Generated by Django 5.0 on 2024-02-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="id",
        ),
        migrations.AlterField(
            model_name="course",
            name="courseID",
            field=models.CharField(
                default="",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
