# Generated by Django 5.0 on 2024-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_id_alter_course_courseid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="courseID",
            field=models.IntegerField(
                default="",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
